apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ${namespace}
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      replicas: ${replicas}
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: ${image_registry}/${image_repository}/frontend:${image_version}
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "${productcatalogservice_name}:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "${currencyservice_name}:7000"
          - name: CART_SERVICE_ADDR
            value: "${cartservice_name}:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "${recommendationservice_name}:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "${shippingservice_name}:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "${checkoutservice_name}:5050"
          - name: AD_SERVICE_ADDR
            value: "${adservice_name}:9555"
          - name: ENV_PLATFORM
            value: "local"
          - name: ENABLE_PROFILER
            value: "0"
          # - name: CYMBAL_BRANDING
          #   value: "true"
          - name: FRONTEND_MESSAGE
            value: "Walrus Demo"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ${namespace}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: ${namespace}
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
